image: docker:24.0.6

services:
  - docker:24.0.6-dind

variables:
  DOCKER_DRIVER: overlay2
  COMPOSER_CACHE_DIR: "/cache/composer"

stages:
  - build
  - test

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - docker-compose -f docker-compose.yml pull
  - docker-compose -f docker-compose.yml build

build:
  stage: build
  script:
    - echo "Build terminé"
  only:
    - main

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose exec -T app composer install
    - docker-compose exec -T app ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main
