services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: php-webe
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    command: >
      sh -c "composer install && php -S 0.0.0.0:80 -t public"

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-databasee
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmine
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db-data:
